version: "3"

services:
  app_server:
    image: "recourser/backend"
    container_name: recourser_server
    build:
      context: backend
      target: production
      dockerfile: backend/Dockerfile
    command: npm run start:prod
    env_file:
      - "backend/.env"
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - recourser
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database

  database:
    container_name: recourser_database
    hostname: "recourser_db"
    image: postgres:12
    env_file: "backend/.env"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - recourser
    ports:
      - "5440:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  recourser:

volumes:
  postgres-data:
