version: '3.9'

services:
  app_server:
    container_name: app_server
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - recourser
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: recourser_db
    image: postgres:12
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - recourser
    ports:
      - '5440:5432'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  recourser:

volumes:
  postgres-data: